INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('11111', '브라이트닝 포어 세럼 30mL', 35000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('22222', '포레스트 포맨 올인원 에센스 4종 100mL', 25000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('33333', '트루케어 AC 진정 앰플 40mL', 28000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('44444', '트루케어 알란토인 워터드롭 에센스 150mL', 28000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('55555', '트루케어 시카 AA 트리트먼트 크림 50mL', 25000, 'C', SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('66666', '그린티 밸런싱 스킨 EX', 25000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('77777', '더 미니멈 토너 45mL', 25000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('88888', '진저허니 앰플 스킨 200mL', 25000, SYSDATE, 'SYSTEM');

INSERT INTO PRODUCT (CODE, NAME, PRICE, CREATE_DATE, CREATE_ID)
VALUES ('99999', '청보리 필링 토너 250mL', 25000, SYSDATE, 'SYSTEM');
