CREATE TABLE PRODUCT (
    PRDSEQ  NUMERIC,
    PRDIMG  VARCHAR(4000),
    PRDNMS  VARCHAR(4000),
    PRDNM   VARCHAR(4000),
    BASICDESC   VARCHAR(4000),
    HASHTAG VARCHAR(4000),
    SALPRC  NUMERIC,
    CPNEXFL BOOLEAN,
    PTUSENAFL   BOOLEAN,
    MEMBERONLYFL    BOOLEAN,
    BTYPTUNPAIDFL   BOOLEAN,
    PURATTNMTS  VARCHAR(4000),
    PRDDTLHTMLURL   VARCHAR(4000),
    PRDVOL  VARCHAR(4000),
    MNUFACT VARCHAR(4000),
    MNUFACTAREA VARCHAR(4000),
    USEENDDATE  VARCHAR(4000),
    PRDUSEDESC  VARCHAR(4000),
    PRDCOMPDESC VARCHAR(4000),
    PRDAUDITDESC    VARCHAR(4000),
    QADESC  VARCHAR(4000),
    PRDELEMENT  VARCHAR(4000),
    USECAREDESC VARCHAR(4000),
    ASDESC  VARCHAR(4000)
)
;

CREATE TABLE OPTION (
   PRDSEQ NUMERIC,
   SAPPRDCD VARCHAR(4000),
   ORDERBY NUMERIC,
   KINDNM VARCHAR(4000),
   BARCODE VARCHAR(4000)
);

CREATE TABLE CATEGORY
(
   CATEGORY_CODE VARCHAR(4000),
   NAME VARCHAR(4000),
   SUPER_CATEGORY_CODE VARCHAR(4000),
   CAT_ORDER NUMERIC
);

CREATE TABLE CATEGORY_PRODUCT (
   CATEGORY_CODE VARCHAR(4000),
   PRDSEQ NUMERIC
);
